### PR TITLE
Action bridge

### PR DESCRIPTION
**Pull request by LoyVanBeek**
This is https://github.com/ros2/ros1_bridge/pull/256 rebased on [`mojin-devel`](https://github.com/mojin-robotics/ros1_bridge).

### CODE REVIEW

**Comment by fmessmer** [comment]
ref https://github.com/schiller-de/amr_platform_orga/issues/60
ref https://github.com/mojin-robotics/cob4/issues/2000

**Comment by fmessmer** [comment]
I updated mojin-robotics/ros1_bridge#master branch to be synced with latest ros2/ros1_bridge#master updates
now this branch has a merge conflict

@LoyVanBeek

**Comment by LoyVanBeek** [comment]
Rebasing is not so easy anymore due to reformatting which makes things harder to see. I tried to re-rebase that didn't work out in the end.

**Comment by fmessmer** [comment]
@LoyVanBeek 
we changed the target branch to `mojin-devel`
as https://github.com/mojin-robotics/ros1_bridge/pull/3 is merged now, this PR has a merge conflict
could you rebase and resolve the conflict and then test the action support another test - see https://github.com/4am-robotics/orga/issues/2503

**Comment by benmaidel** [comment]
I've rebased the action_bridge on top of mojin-devel. I've added a new branch with the rebased version here https://github.com/benmaidel/ros1_bridge/tree/action_bridge. 
When tests are successful I'll force-push onto this branch

**Comment by LoyVanBeek** [comment]
Tested successfully & OK in https://github.com/4am-robotics/orga/issues/2503#issuecomment-1252013415 so good to force-push and merge IMO

**Pull request merged**
