### PR TITLE
Account for fields mapped by rules when checking for missed fields

### PR DESCRIPTION
**Pull request by LoyVanBeek**
Fixup for #4 and https://github.com/ros2/ros1_bridge/pull/382 applied on top of `mojin-devel`

The code after the early return mentioned in the previous commit assumed all fields would match by name, which was of course true. But not anymore, so the missing check now only fails when the missing fields are also not already accounted for via a mapping

To test:
Put 
```yaml
  - topic: /test_id
    type: unique_identifier_msgs/msg/UUID
    queue_size: 1
  - topic: /gazebo_stuff
    type: gazebo_msgs/msg/ODEJointProperties
    queue_size: 1
```

in eg. `amr_config/robots/common/ros1_ros2_bridge.yaml`
and start `source_amr_ros_bridge && ROBOT=mrl-2 start_amr_ros_bridge`

Then run
```bash
source_amr_ros2 && ros2 topic pub /test_id unique_identifier_msgs/msg/UUID "uuid: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2]"

source_amr_ros1 && rostopic echo /test_id
```

```bash
source_amr_ros1 && rostopic pub /test_id uuid_msgs/UniqueID "uuid: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]" -r1

source_amr_ros2 && ros2 topic echo /test_id
```

```bash
source_amr_ros2 && ros2 topic pub /gazebo_stuff gazebo_msgs/msg/ODEJointProperties "damping: []
hi_stop: [10]
lo_stop: [11]
erp: [12]
cfm: [13]
stop_erp: [14]
stop_cfm: [15]
fudge_factor: [16]
fmax: [17]
vel: [18]" -r 1

source_amr_ros1 && rostopic echo /gazebo_stuff
```

```bash
source_amr_ros1 && rostopic pub /gazebo_stuff gazebo_msgs/ODEJointProperties "damping: [1]
hiStop: [2]
loStop: [3]
erp: [4]
cfm: [5]
stop_erp: [6]
stop_cfm: [7]
fudge_factor: [8]
fmax: [9]
vel: [10]"  -r 1

source_amr_ros2 && ros2 topic echo /gazebo_stuff gazebo_msgs/msg/ODEJointProperties
```

### CODE REVIEW

**Review by fmessmer — CHANGES_REQUESTED** [review]
please rebase
then see which colcon tests are easy to fix, fix them....disable the others in the ci config/CMakeLists.txt/...

**Review by fmessmer — CHANGES_REQUESTED** [review]
still a few tests fail:
```
  4: Working Directory: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/lj3oo2knegi/ros1_bridge
  4: Test timeout computed to be: 60
  4: -- run_test.py: invoking following command in '/home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/lj3oo2knegi/ros1_bridge':
  4:  - /opt/ros/foxy/bin/ament_flake8 --xunit-file /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml
  4: 
  4: ./ros1_bridge/__init__.py:469:1: B902 blind except Exception: statement
  4:                     except Exception as e:
  4: ^
  4: 
  4: 1     B902 blind except Exception: statement
  4: 
  4: 1 files checked
  4: 1 errors
  4: 
  4: 'B'-type errors: 1
  4: 
  4: Checked files:
  4: 
  4: * ./ros1_bridge/__init__.py
  4: -- run_test.py: return code 1
  4: -- run_test.py: verify result file '/home/runner/work/ros1_bridge/ros1_bridge/ros_ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml'
   4/12 Test  #4: flake8 .....................................................***Failed    1.31 sec
  test 5
        Start  5: lint_cmake
```

**Comment by LoyVanBeek** [comment]
Well shit, this one is not super trivial: the action mapping code raises a plain `Exception`, which needs to be caught. To squelch the formatting error, I need to introduce a new custom Exception type I think. Hmm

**Review by fmessmer — CHANGES_REQUESTED** [review]
still some issues in `rolling`:
```
  7: Code style divergence in file 'include/ros1_bridge/action_factory.hpp':
  7: 
  7: --- include/ros1_bridge/action_factory.hpp
  7: +++ include/ros1_bridge/action_factory.hpp.uncrustify
  7: @@ -397 +397 @@
  7: -    return std::hash<rclcpp_action::GoalUUID>{} (uuid);
  7: +    return std::hash<rclcpp_action::GoalUUID>{}(uuid);
  7: 
  7: 1 files with code style divergence
```
and
```
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/include/ros1_bridge/builtin_interfaces_factories.hpp:26:  Found C++ system header after other header. Should be: builtin_interfaces_factories.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/include/ros1_bridge/builtin_interfaces_factories.hpp:27:  Found C++ system header after other header. Should be: builtin_interfaces_factories.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:17:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:18:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:19:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:20:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:21:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:22:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: /home/runner/work/ros1_bridge/ros1_bridge/ros_ws/src/l1bg7w74dsn/ros1_bridge/src/dynamic_bridge.cpp:23:  Found C++ system header after other header. Should be: dynamic_bridge.h, c system, c++ system, other.  [build/include_order] [4]
  3: Category 'build/include_order' errors found: 9
  3: Total errors found: 9
```

**Comment by LoyVanBeek** [comment]
Heh, the code styles don't agree it seems. 
Locally:
```
Code style divergence in file 'include/ros1_bridge/action_factory.hpp':

--- include/ros1_bridge/action_factory.hpp
+++ include/ros1_bridge/action_factory.hpp.uncrustify
@@ -397 +397 @@
-    return std::hash<rclcpp_action::GoalUUID>{}(uuid);
+    return std::hash<rclcpp_action::GoalUUID>{} (uuid);

1 files with code style divergence
```

which is the opposite of the above. I specifically looked at the include ordering myself (and remember because it was annoying to figure out what was correct) so I think the style changed for `rolling`. Not sure how to continue, besides disabling `rolling`.

**Comment by fmessmer** [comment]
~~ok, I'll disable `rolling`~~
I cannot push to your branch - but rolling is disabled on `mojin-devel`
can you rebase this PR?

**Comment by fmessmer** [comment]
as this has been going back and forth, I want to give this a proper review next week

**Review by fmessmer — APPROVED** [review]
successfully tested all (known) cases where we had issues before, i.e. uuid_msgs and gazebo_msgs (as described by @LoyVanBeek)

**Pull request merged**
