### PR TITLE
ros1_bridge fixes

### PR DESCRIPTION
**Pull request by benmaidel**
ref:
- https://github.com/4am-robotics/orga/issues/2540
- https://github.com/4am-robotics/orga/issues/2536

fixes:
- do not throw std::runtime exceptions on failed ros1 service calls. To catch and handle them at this location, modifications to the idl needs to take place
- enable multithreaded spinners to allow concurrent service handling
- periodically update the services on parameter_bridge like the dynamic_bridge to allow recovery of lost services
- clean up

### CODE REVIEW

**Review by LoyVanBeek — COMMENTED** [review]
I like the cleanup, but not sure if it will be accepted easily upstream.

I'll try to test this PR where I can too

**Comment by LoyVanBeek** [comment]
- :heavy_check_mark: Reconnecting ROS 1 service servers after a restart with dynamic bridge
- :heavy_check_mark: Reconnecting ROS 2 service servers after a restart with dynamic bridge
- :heavy_check_mark: Reconnecting ROS 1 service servers after a restart with parameter bridge
- :heavy_check_mark: Reconnecting ROS 2 service servers after a restart with parameter bridge
- :heavy_check_mark: Crashes in a ROS 1 services handled OK (except some formatting, but logic works). 
- :heavy_check_mark: Crash in ROS 2 service handled OK. 
   - There is something weird though: I tried `rosservice call /get_segment_plan` with frame_id's set to map and goal x,y = (10, 10). This somehow throws an exception in the service, so that confirms that the bridge stays alive. The equivalent `ros2 service call` works without any issues and shows the resulting segment plan.
   - Same for `rosservice call /get_segments "{}"`, I get back `ERROR: service [/get_segments] responded with an error: b''` while the ros2 equivalent works perfectly fine. 

@benmaidel can you reproduce this?

**Comment by benmaidel** [comment]
> I like the cleanup, but not sure if it will be accepted easily upstream.

right, that could be a problem.

Another thing, if you like the test the multithreaded services (call a service while another is still active) you have to start the dynamic_bridge or parameter_bridge with the command line argument `--multi-thread`

**Comment by LoyVanBeek** [comment]
What I ran to test this:
```bash
source_amr_ros1 && roscore
source_amr_ros1 && roslaunch afi_bringup emulator.launch robot:=afi-l15 robot_env:=schiller-metten-testhalle license_server_address:=10.0.1.2

source_amr_ros2 && colcon_cd amr_path_planning_bringup && ros2 launch -a amr_path_planning_bringup amr_path_planning_launch.py road_network_file:=config/RoadNetworkTest_Rückwärts3.srntransferx; cd -

source_amr_ros_bridge && ROBOT=afi-l15 start_amr_ros_bridge
```
which uses the `dynamic_bridge`
and then call `/get_segments` from both sides of the bridge.

For the parameter_bridge, I used this config file:
```yaml
# ~/bridge.yaml
topics: []
services_1_to_2:
  - service: /get_segment_plan  # ROS2 service name
    type: nav_msgs/srv/GetPlan
  - service: /get_segments  # ROS2 service name
    type: amr_road_network_msgs/srv/GetSegments
services_2_to_1:
  - service: /operation_mode_command  # ROS 1 name & type
    type: amr_msgs/OperationModeCommand
```
and ran `rosparam load ~/bridge.yaml && ros2 run ros1_bridge parameter_bridge` to test the `parameter_bridge`

**Comment by benmaidel** [comment]
I've just tried to reproduce what @LoyVanBeek experienced. I did not had a problem calling the `\get_segments` service from ros1 and ros2. @LoyVanBeek I think the problem was to not use the new `multi-thread` feature. I've updated the amr scripts, so the `m̀ulti-thread` feature is used by default. https://github.com/mojin-robotics/setup_cob4/pull/411
I tried it with `fastRtps`and `cyclonDDS`. On both the same result.
@LoyVanBeek can you please retry it with the updated amr scripts and the latest ros1_bridge version?

**Comment by fmessmer** [comment]
should we merge this PR to `mojin-robotics/master` - or better to some new `mojin-robotics/mojin-devel` branch?
I'd prefere `mojin-robotics/mojin-devel` so we can keep `mojin-robotics/master` in sync with `ros2/master`

**Review by fmessmer — APPROVED** [review]
my tests might not have been as excessive - but I could not observer any issues when running the `amr_path_planning` example with `afi-l15`

**Comment by LoyVanBeek** [comment]
With the latest merges everything seems to run fine indeed.
The default executable for `ros1_bridge` is now `parameter_bridge` again, with `--multi-threads` enabled.
Curious to try without that flag as well. 

- [x] :heavy_check_mark: `parameter_bridge --multi-threads` in normal transferjob operation
- [x] :heavy_check_mark: `parameter_bridge` single threaded: in normal transferjob operation
- [x] :heavy_check_mark: Reconnecting ROS 2 service servers after a restart with `parameter_bridge` single threaded: returns `b''` when calling `/get_segments` 2x in parallel. It's a silent failure but to be expected in single threaded application I suppose. Being aware of that limitation is enough for us, getting this known and fixed upstream would be nice, but not required. 
- [x] :heavy_check_mark: Reconnecting ROS 1 service servers after a restart with `parameter_bridge` single threaded: 
- [x] :heavy_check_mark: Reconnecting ROS 1 service servers after a restart with `parameter_bridge --multi-threads`
- [x] :heavy_check_mark: Reconnecting ROS 2 service servers after a restart with `parameter_bridge --multi-threads`
- [x] :heavy_check_mark: Reconnecting ROS 1 service servers after a restart with dynamic bridge
- [x] :heavy_check_mark: Reconnecting ROS 2 service servers after a restart with dynamic bridge
- [x] :heavy_check_mark: Crash in a ROS 1 service: handled OK, we get and error message like `Service call failed: service [/update_aggregated_alert_info] responded with an error: error processing request: 
[ros_bridge:forward_2_to_1:325][ERROR] [1662990813.357060112]: Failed to get response from ROS 1 service �I` . The formatting is a bit off though!
- [x] :heavy_check_mark: Crash in a ROS 2 service: returns a `b''` when the service itself throws an exception. Can't expect more really.

**Pull request merged**
